### ISSUE TITLE
TypeError in 3.3.2

### ISSUE THREAD

**Issue by kylecotter** [angell-co/Spoon#52]
Hi Josh!

Just updated to the latest version of Spoon and get

`Argument 1 passed to craft\services\Matrix::getBlockTypeById() must be of the type integer, null given, called in /var/www/vendor/angellco/spoon/src/controllers/BlockTypesController.php on line 88`

when navigating to the new CP side nav link.

Do I need to trigger a re-save on something? I believe that error is in reference to the new functionality added.

Thanks!

**Comment by joshangell** [comment]
Thanks for this @kylecotter - given it worked for my setup could you send me a copy of your database and composer.json to josh@angell.io? I’ll be able to fully debug it then.

Cheers!

**Comment by joshangell** [comment]
OK, I have done a sanity check anyway so that this error should go away, but you probably won’t be able to see all the Matrix > Super Table > Matrix fields you’re expecting. I’m not sure why but somehow its managed to load the Matrix and Super Table but not the nested Matrix field, perhaps try re-saving the fields?

**Comment by kylecotter** [comment]
@joshangell Thanks! Update did the trick. Everything seems listed properly too. Re-saved everything for good measure.
