### ISSUE TITLE
3.4.1 is showing up in Craft updates but not coming down via `composer update`

### ISSUE THREAD

**Issue by bossanova808** [angell-co/Spoon#74]
https://github.com/angell-co/Spoon/blob/f5b9fb78223a7571291bf2827200485df409d340/src/Spoon.php#L69

Probably because this version number is still 3.4.0?

**Comment by joshangell** [comment]
Hi Jeremy - this is because I made the unfortunate mistake of requiring PHP >= 7.1 for this release, purely because I’ve started using the new type-hints.

This is conflicting with the core Craft composer requirement of PHP >= 7.0.0 ... to get around it for now you can change the platform reference in your project’s `composer.json`:

```
"config": {
  "platform": {
    "php": "7.1"
  }
},
```

Only do this if you want to carry on with the upgrade and are actually running PHP >= 7.1, otherwise wait for the patch release to come out, which should be Monday now after I have removed the code that relies on PHP 7.1.

**Comment by bossanova808** [comment]
No problems Josh, I'll just wait I think.  Although I am using 7.2 on both dev and production, just in case of other implications I'd probably prefer not to mess with the core requirements...

**Comment by joshangell** [comment]
Hi Jeremy, this requirement has been removed now in the latest release. Thanks for your patience!
