### ISSUE TITLE
Safari becomes unresponsive when configuring layouts

### ISSUE THREAD

**Issue by jeffaglenn** [angell-co/Spoon#8]
Really weird issue of Safari using a ton of resources, becoming unresponsive, and basically crashing when organizing the spoon layouts. Used Chrome and everything was okay. Let me know if I can help diagnose this a little better.

**Comment by theskyfloor** [comment]
Same here.

**Comment by joshangell** [comment]
OK, I have tracked this down to a possible issue inside the core `Craft.Grid` class, which has [this innocuous line](https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/Grid.js#L347):

```
this.addListener(this.$container, 'resize', this.handleContainerHeightProxy);
```

For some reason when the `Craft.FieldLayoutDesigner` class is loaded inside a modal there are multiple resize events being added to the container in question, which causes an infinite loop.

Simply changing that line to the following does seem to fix it:

```
if ($.inArray(this.$container, this._listeners) === -1) {
    this.addListener(this.$container, 'resize', this.handleContainerHeightProxy);
}
```

I will PR the core repo, but it may have consequences I’m not aware of so it should be thought through further.

To clarify, this only happens in Safari because it seems other browsers throttle the infinite loop behaviour so as not to crash. It is technically happening in all browsers.

**Comment by joshangell** [comment]
OK, small update on this one - its been fixed in the core, so when the next Craft release gets pushed I’ll double check it fixes our issue and cut a new release for Spoon.

Thanks for your patience!
